// src/containers/glassesData.js

export const glassesData = [
  { id: 1, src: '/images/glasses/1.png', name: '' },
  { id: 2, src: '/images/glasses/2.png', name: '' },
  { id: 3, src: '/images/glasses/3.png', name: '' },
  { id: 4, src: '/images/glasses/4.png', name: '' },
  { id: 5, src: '/images/glasses/5.png', name: '' },
  { id: 6, src: '/images/glasses/6.png', name: '' },
  { id: 7, src: '/images/glasses/7.png', name: '' },
  { id: 8, src: '/images/glasses/8.png', name: '' },
  { id: 9, src: '/images/glasses/9.png', name: '' },
  { id: 10, src: '/images/glasses/10.png', name: '' },
  { id: 11, src: '/images/glasses/12.png', name: '' },
  { id: 12, src: '/images/glasses/13.png', name: '' },
  { id: 13, src: '/images/glasses/14.png', name: '' },
  { id: 14, src: '/images/glasses/15.png', name: '' },
  { id: 15, src: '/images/glasses/16.png', name: '' },
  { id: 16, src: '/images/glasses/17.png', name: '' },
  { id: 17, src: '/images/glasses/18.png', name: '' },
  { id: 18, src: '/images/glasses/19.png', name: '' },
  { id: 19, src: '/images/glasses/20.png', name: '' },
  { id: 20, src: '/images/glasses/21.png', name: '' },
  { id: 13, src: '/images/glasses/22.png', name: '' },
  { id: 14, src: '/images/glasses/23.png', name: '' },
  { id: 15, src: '/images/glasses/24.png', name: '' },
  { id: 16, src: '/images/glasses/25.png', name: '' },
  { id: 17, src: '/images/glasses/26.png', name: '' },
  { id: 18, src: '/images/glasses/27.png', name: '' },
  { id: 19, src: '/images/glasses/28.png', name: '' },
  { id: 20, src: '/images/glasses/29.png', name: '' },
  { id: 13, src: '/images/glasses/30.png', name: '' },
  { id: 14, src: '/images/glasses/31.png', name: '' },
  { id: 15, src: '/images/glasses/32.png', name: '' },
  { id: 16, src: '/images/glasses/33.png', name: '' },

];
